# Übungen zu Vorlesung 1 – Lineare Regression

## **1. Anwendung der Linearen Regression (birthweight_data.csv)**

Nutzt das in der Vorlesung besprochene theoretische und praktische Vorgehen zur Anwendung der Linearen Regression in Python, basierend auf den Daten in `birthweight_data.csv`.  
Das *Geburtsgewicht des Kindes* ist hier die Output-Variable.

Da lineare Regression viele unterschiedliche Fragen beantworten kann, gibt es verschiedene mögliche Analysen.

Beispielhafte Analysefragen:

### **a.**  
Im einfachen linearen Regressionsmodell mit *nur `cigs`* als erklärende Variable:  
**Wie viele Zigaretten müsste die Mutter während der Schwangerschaft rauchen, damit ein Geburtsgewicht von 125 Unzen erreicht wird?**  
Kommentiert und erklärt das Ergebnis.

---

### **b.**  
(Ohne Python)  
Wenn das *Familieneinkommen* in das Modell aus (a) hinzugefügt wird, welches **Vorzeichen** hätte der Koeffizient wahrscheinlich?  
Sind **Zigarettenkonsum** und **Familieneinkommen** korreliert?  
Ist die Korrelation positiv oder negativ?

Überprüft eure Annahmen mit Python und vergleicht das Ergebnis mit der Regression aus (a).

---

### **c.**  
Im Modell mit **allen erklärenden Variablen**:  
Welche Einflussfaktoren haben **statistische** und **praktische Signifikanz**?  
Welche Faktoren haben einen positiven bzw. negativen Einfluss?  
Interpretiert die Ergebnisse.

---

### **d.**  
Welche **einfache lineare Regression** (mit nur einer erklärenden Variable) kann das Geburtsgewicht am besten erklären?  
Visualisiert diese Beziehung.

Was bedeuten der **Koeffizient** und der **Y-Achsenabschnitt**?

---

### **e.**  
Welchen Einfluss hat das **Familieneinkommen (`faminc`)** auf das Geburtsgewicht?  
Ist der Einfluss **statistisch signifikant**?

---

### **f.**  
Welche **funktionale Form** des Familieneinkommens eignet sich am besten für die Regression?  
(z. B. log, Wurzel, polynomielle Formen)

---

### **g.**  
Welche Interaktionen der quantitativen Variable **`male`** sind statistisch signifikant und sollten in das Modell aufgenommen werden?  
Wie sind diese Interaktionen zu interpretieren?

---

### **h.**  
Welche **lineare Regression** erklärt das Geburtsgewicht insgesamt am besten?  
Wie hoch sind der **R²-Wert** und die **SSR** (Sum of Squared Residuals)?

---

### **i.**  
Welche **zusätzlichen Daten** könnten in das Modell aufgenommen werden, um es zu verbessern?

---

### **j.**  
Welche weiteren interessanten Erkenntnisse könnt ihr mit linearer Regression aus den Daten gewinnen?  
Was sind die **Limitationen** des Ansatzes?

---

# Vorgehensweise
## 1.Daten vorbereiten

In [1]:
import pandas as pd

### Daten laden

In [4]:
birthweight_data = pd.read_csv('../Data/Raw/birthweight_data.csv')
birthweight_data.head()

,faminc,cigtax,cigprice,bwght,fatheduc,motheduc,parity,male,white,cigs,bwghtlbs
0,13.5,16.5,122.300003,109,12.0,12.0,1,1,1,0,6.8125
1,7.5,16.5,122.300003,133,6.0,12.0,2,1,0,0,8.3125
2,0.5,16.5,122.300003,129,NaN,12.0,2,0,0,0,8.0625
3,15.5,16.5,122.300003,126,12.0,12.0,2,1,0,0,7.8750
4,27.5,16.5,122.300003,134,14.0,12.0,2,1,1,0,8.3750

### Daten prüfen

In [5]:
birthweight_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1388 entries, 0 to 1387
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   faminc    1388 non-null   float64
 1   cigtax    1388 non-null   float64
 2   cigprice  1388 non-null   float64
 3   bwght     1388 non-null   int64
 4   fatheduc  1192 non-null   float64
 5   motheduc  1387 non-null   float64
 6   parity    1388 non-null   int64
 7   male      1388 non-null   int64
 8   white     1388 non-null   int64
 9   cigs      1388 non-null   int64
 10  bwghtlbs  1388 non-null   float64
dtypes: float64(6), int64(5)
memory usage: 119.4 KB

### Fehlende Daten

In [6]:
birthweight_data.isna().mean()

faminc      0.00000
cigtax      0.00000
cigprice    0.00000
bwght       0.00000
fatheduc    0.14121
motheduc    0.00072
parity      0.00000
male        0.00000
white       0.00000
cigs        0.00000
bwghtlbs    0.00000
dtype: float64

In [ ]:
# Entfernen der Reihen mit NA Werten:
birthweight_data.dropna()

,faminc,cigtax,cigprice,bwght,fatheduc,motheduc,parity,male,white,cigs,bwghtlbs
0,13.5,16.5,122.300003,109,12.0,12.0,1,1,1,0,6.8125
1,7.5,16.5,122.300003,133,6.0,12.0,2,1,0,0,8.3125
3,15.5,16.5,122.300003,126,12.0,12.0,2,1,0,0,7.8750
4,27.5,16.5,122.300003,134,14.0,12.0,2,1,1,0,8.3750
5,7.5,16.5,122.300003,118,12.0,14.0,6,1,0,0,7.3750
...,...,...,...,...,...,...,...,...,...,...,...
1381,12.5,30.0,138.300003,87,14.0,12.0,1,1,1,0,5.4375
1382,22.5,30.0,138.300003,135,16.0,16.0,3,0,1,0,8.4375
1383,27.5,30.0,138.300003,110,12.0,12.0,4,1,1,0,6.8750
1385,65.0,8.0,118.599998,135,18.0,16.0,2,0,1,0,8.4375
1387,37.5,8.0,118.599998,111,16.0,13.0,2,0,1,0,6.9375

In [8]:
# Entfernen der Spalten mit NA Werten:
birthweight_data.dropna(axis=1)

      faminc  cigtax    cigprice  bwght  parity  male  white  cigs  bwghtlbs
0       13.5    16.5  122.300003    109       1     1      1     0    6.8125
1        7.5    16.5  122.300003    133       2     1      0     0    8.3125
2        0.5    16.5  122.300003    129       2     0      0     0    8.0625
3       15.5    16.5  122.300003    126       2     1      0     0    7.8750
4       27.5    16.5  122.300003    134       2     1      1     0    8.3750
...      ...     ...         ...    ...     ...   ...    ...   ...       ...
1383    27.5    30.0  138.300003    110       4     1      1     0    6.8750
1384     5.5    30.0  138.300003    146       2     1      1     0    9.1250
1385    65.0     8.0  118.599998    135       2     0      1     0    8.4375
1386    27.5     8.0  118.599998    118       2     0      1     0    7.3750
1387    37.5     8.0  118.599998    111       2     0      1     0    6.9375

[1388 rows x 9 columns]

In [9]:
# Ersetzen der fehlenden Daten durch Mittelwert / Median / Modus 
birthweigh_filled_copy = birthweight_data.copy()
birthweigh_filled_copy["fatheduc"] = birthweight_data["fatheduc"].fillna(birthweight_data["fatheduc"].mean())
birthweigh_filled_copy["motheduc"] = birthweight_data["motheduc"].fillna(birthweight_data["motheduc"].median())
birthweigh_filled_copy.isna().sum()
birthweigh_filled_copy

,faminc,cigtax,cigprice,bwght,fatheduc,motheduc,parity,male,white,cigs,bwghtlbs
0,13.5,16.5,122.300003,109,12.000000,12.0,1,1,1,0,6.8125
1,7.5,16.5,122.300003,133,6.000000,12.0,2,1,0,0,8.3125
2,0.5,16.5,122.300003,129,13.186242,12.0,2,0,0,0,8.0625
3,15.5,16.5,122.300003,126,12.000000,12.0,2,1,0,0,7.8750
4,27.5,16.5,122.300003,134,14.000000,12.0,2,1,1,0,8.3750
...,...,...,...,...,...,...,...,...,...,...,...
1383,27.5,30.0,138.300003,110,12.000000,12.0,4,1,1,0,6.8750
1384,5.5,30.0,138.300003,146,13.186242,16.0,2,1,1,0,9.1250
1385,65.0,8.0,118.599998,135,18.000000,16.0,2,0,1,0,8.4375
1386,27.5,8.0,118.599998,118,13.186242,14.0,2,0,1,0,7.3750
1387,37.5,8.0,118.599998,111,16.000000,13.0,2,0,1,0,6.9375

In [10]:
# Nutzen der sklearn Methoden oder manuelle Implementierung
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer # Alternative: KNNImputer
imputer = IterativeImputer(random_state=0).set_output(transform="pandas")
birthweigh_filled_copy = imputer.fit_transform(birthweight_data)
print("Number of NA values: ", birthweigh_filled_copy.isna().sum().sum())

Number of NA values:  0

In [11]:
birthweigh_filled_copy

,faminc,cigtax,cigprice,bwght,fatheduc,motheduc,parity,male,white,cigs,bwghtlbs
0,13.5,16.5,122.300003,109.0,12.000000,12.0,1.0,1.0,1.0,0.0,6.8125
1,7.5,16.5,122.300003,133.0,6.000000,12.0,2.0,1.0,0.0,0.0,8.3125
2,0.5,16.5,122.300003,129.0,11.398633,12.0,2.0,0.0,0.0,0.0,8.0625
3,15.5,16.5,122.300003,126.0,12.000000,12.0,2.0,1.0,0.0,0.0,7.8750
4,27.5,16.5,122.300003,134.0,14.000000,12.0,2.0,1.0,1.0,0.0,8.3750
...,...,...,...,...,...,...,...,...,...,...,...
1383,27.5,30.0,138.300003,110.0,12.000000,12.0,4.0,1.0,1.0,0.0,6.8750
1384,5.5,30.0,138.300003,146.0,14.486050,16.0,2.0,1.0,1.0,0.0,9.1250
1385,65.0,8.0,118.599998,135.0,18.000000,16.0,2.0,0.0,1.0,0.0,8.4375
1386,27.5,8.0,118.599998,118.0,13.407292,14.0,2.0,0.0,1.0,0.0,7.3750
1387,37.5,8.0,118.599998,111.0,16.000000,13.0,2.0,0.0,1.0,0.0,6.9375

In [12]:
# Number of changed values:
(birthweigh_filled_copy != birthweight_data).sum()

faminc        0
cigtax        0
cigprice      0
bwght         0
fatheduc    196
motheduc      1
parity        0
male          0
white         0
cigs          0
bwghtlbs      0
dtype: int64